stages:
  - publish

publish:
  stage: publish
  only: [master] 
  script:
    - cp ./.ci/.npmrc ./.npmrc && npm i && node updatePackageVersion.js && npm run build && cd ./dist && npm publish && rm -rf .npmrc

