stages:
  - publish

publish:
  stage: publish
  only: [master] 
  script:
    - cp ./.ci/.npmrc ./.npmrc 
    - nvm install 16.18.0
    - nvm use 16.18.0
    - npm i
    - npm run build 
    - cd ./dist && npm publish && cd .. && rm -rf ./.npmrc
