stages:
  - publish

publish:
  stage: publish
  only: [master] 
  script:
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    - nvm install 16
    - nvm use 16
    - cp ./.ci/.npmrc ./.npmrc 
    - npm i 
    - npm run build 
    - cd ./dist && npm publish && cd .. && rm -rf ./.npmrc
