stages:
  - publish

publish:
  stage: publish
  only: [main] 
  script:
    - >
     export NVM_DIR="$HOME/.nvm" 
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" 
    - nvm install 20.8.0
    - npm i --force --legacy-peer-deps
    - npm run build 
    - cp ./.ci/.npmrc dist
    - cd dist && npm publish

publish_dev:
  stage: publish
  only: [next]
  script:
    - >
     export NVM_DIR="$HOME/.nvm" 
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" 
    - nvm install 20.8.0
    - npm i --force --legacy-peer-deps
    - npm run build
    - cp ./.ci/.npmrc dist
    - cd dist && ../.ci/dev-version.sh
