export * from './dish/dish.gql';
export * from './group/group.gql';
export * from './group-modifier/group-modifier.gql';
export * from './image/image.gql';
export * from './modifier/modifier.gql';
export * from './navigation/navigation.gql';
export * from './order';
export * from './order-dish/order-dish.gql';;
export * from './payment-method/payment-method.gql';
export * from './event-message/event-message';
export * from './maintenance/maintenance';
export * from './customer';
export { NgGqlConfig } from './ng-gql-config/ng-gql-config';
export { deepClone } from './deep-clone';
export { ValuesOrBoolean } from './values-or-boolean';
export { generateQueryString } from './generate-query-string';
export { VCriteria, GQLRequestVariables } from './generate-query-string';
export * from './order-bus-event';
export { BaseModelWithCustomData } from './base/base-model-with-custom-data';
export { NqGqlLocalStorageWrapper } from './storage-wrapper/storage-wrapper';